### ISSUE TITLE
添加了zabbix-server-mysql-sendEmail，zabbix-server报错

### ISSUE THREAD

**Issue by BairubingAO** [fivestrong/zabbix-grafana-docker#2]
[root@zabbix zabbix-server-mysql-sendEmail]# docker logs zabbix-server
/bin/bash: /run_zabbix_component.sh: No such file or directory
/bin/bash: /run_zabbix_component.sh: No such file or directory
/bin/bash: /run_zabbix_component.sh: No such file or directory
/bin/bash: /run_zabbix_component.sh: No such file or directory
/bin/bash: /run_zabbix_component.sh: No such file or directory

**Comment by fivestrong** [comment]
> [root@zabbix zabbix-server-mysql-sendEmail]# docker logs zabbix-server
> /bin/bash: /run_zabbix_component.sh: No such file or directory
> /bin/bash: /run_zabbix_component.sh: No such file or directory
> /bin/bash: /run_zabbix_component.sh: No such file or directory
> /bin/bash: /run_zabbix_component.sh: No such file or directory
> /bin/bash: /run_zabbix_component.sh: No such file or directory

这个我记得当时添加了之后容器无限重启，具体原因没去研究。我现在用官方自带的发送邮件功能，readme里面有描述，如果官方的不能满足需求可以考虑自己编写python 邮件脚本，然后添加到zabbix中，网上应该有相关的教程。
